hosting_users:
  - username: devops
    php_versions:
      - "8.1"
      - "8.2"
    domains:
      - domain: auto.rfan.my.id
        php_version: "8.2"
        subdomains:
          - { name: "blog" }
          - { name: "shop" }
          - { name: "api" }
    groups:
      - wheel
    php_custom_settings:
      max_execution_time: 600
      memory_limit: 512M